from turtle import *
def koch(l,d):
    if d>1:
        pd()
        koch(l/3,d-1)
        lt(90)
        koch(l/3,d-1)
        rt(90)
        koch(l/3,d-1)
        rt(90)
        koch(l/3,d-1)
        lt(90)
        koch(l/3,d-1)
        pu()
    else:
        pd()
        fd(l/3)
        lt(90)
        fd(l/3)
        rt(90)
        fd(l/3)
        rt(90)
        fd(l/3)
        lt(90)
        fd(l/3)
        pu()
home()
clear()
L = int(input())
D = int(input())
speed(0)
pu();bk(L/2);pd()
koch(L,D)
done()